In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import pairwise_distances
from sklearn.metrics import mean_squared_error

import math

In [2]:
rs_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']

ratings_base = pd.read_csv('ml-100k/ua.base', sep='\t', names=rs_cols, encoding='latin-1')
ratings_test = pd.read_csv('ml-100k/ua.base', sep='\t', names=rs_cols, encoding='latin-1')

In [3]:
n_users_base = ratings_base['user_id'].unique().max()
n_items_base = ratings_base['movie_id'].unique().max()

n_users_base,n_items_base

(943, 1682)

In [4]:
n_users_test = ratings_test['user_id'].unique().max()
n_items_test = ratings_test['movie_id'].unique().max()
n_users_test,n_items_test

(943, 1682)

In [5]:
train_matrix = np.zeros((n_users_base, n_items_base))

In [6]:
test_matrix = np.zeros((n_users_test, n_items_test))

In [7]:
for line in ratings_base.itertuples():
    train_matrix[line[1]-1,line[2]-1] = line[3]

In [8]:
test_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
train_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [10]:
arr=np.array([[1,2,3,],[4,5,6],[7,8,9]])#train matrix
arr2=np.array([[0,0,0],[0,0,0],[0,0,0]])#test matrix

In [11]:
arr2[0]=arr[0]

In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
arr[0]=0

In [15]:
arr

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
n_users_base

943

In [18]:
random_users_id_list=[]
while True:
    rnd=np.random.randint(943)
    if len(random_users_id_list) < 94:
        if rnd in random_users_id_list:
            continue
        else:
            random_users_id_list.append(rnd)
    else:
        break

In [19]:
random_users_id_list.sort()

In [20]:
random_users_id_list

[4,
 12,
 13,
 17,
 19,
 32,
 40,
 59,
 70,
 82,
 100,
 110,
 119,
 128,
 130,
 148,
 150,
 159,
 160,
 175,
 210,
 213,
 224,
 225,
 232,
 242,
 250,
 275,
 277,
 278,
 295,
 305,
 317,
 325,
 326,
 327,
 332,
 355,
 369,
 386,
 395,
 400,
 420,
 431,
 438,
 460,
 462,
 481,
 491,
 492,
 507,
 511,
 519,
 549,
 550,
 556,
 559,
 563,
 584,
 598,
 604,
 616,
 630,
 643,
 652,
 658,
 690,
 721,
 722,
 725,
 745,
 750,
 755,
 757,
 784,
 795,
 801,
 806,
 815,
 816,
 823,
 852,
 863,
 872,
 877,
 880,
 883,
 890,
 912,
 913,
 917,
 919,
 933,
 935]

# 94 kullanıcın oy verdikleri ilk itemleri ve ratingleri  bulup tutmak

In [21]:
users_first_rating_movie=[]

her user verdiği oylardan random seçilecek

In [22]:
for user in random_users_id_list:
    for item in range(n_items_base):
        if train_matrix[user][item] == 0:
            continue
        else:
            users_first_rating_movie.append(item)
            break

In [23]:
print(random_users_id_list)


[4, 12, 13, 17, 19, 32, 40, 59, 70, 82, 100, 110, 119, 128, 130, 148, 150, 159, 160, 175, 210, 213, 224, 225, 232, 242, 250, 275, 277, 278, 295, 305, 317, 325, 326, 327, 332, 355, 369, 386, 395, 400, 420, 431, 438, 460, 462, 481, 491, 492, 507, 511, 519, 549, 550, 556, 559, 563, 584, 598, 604, 616, 630, 643, 652, 658, 690, 721, 722, 725, 745, 750, 755, 757, 784, 795, 801, 806, 815, 816, 823, 852, 863, 872, 877, 880, 883, 890, 912, 913, 917, 919, 933, 935]


In [24]:
print(users_first_rating_movie)

[20, 0, 6, 0, 0, 244, 0, 6, 5, 0, 0, 241, 0, 241, 8, 244, 0, 0, 14, 6, 8, 6, 21, 8, 3, 0, 0, 0, 244, 0, 0, 12, 3, 0, 0, 3, 99, 257, 13, 0, 0, 0, 3, 0, 6, 8, 0, 49, 44, 0, 0, 49, 99, 0, 1, 11, 0, 49, 9, 0, 0, 16, 287, 116, 0, 3, 63, 12, 8, 0, 0, 0, 0, 3, 49, 0, 6, 0, 242, 6, 242, 257, 0, 258, 7, 0, 13, 14, 0, 215, 0, 244, 0, 0]


In [25]:
for i in range(94):
    print(train_matrix[random_users_id_list[i]][users_first_rating_movie[i]], end=", ")

3.0, 3.0, 5.0, 5.0, 3.0, 3.0, 4.0, 5.0, 3.0, 4.0, 3.0, 4.0, 4.0, 4.0, 5.0, 3.0, 5.0, 4.0, 2.0, 5.0, 3.0, 5.0, 5.0, 5.0, 3.0, 4.0, 4.0, 5.0, 3.0, 3.0, 5.0, 4.0, 2.0, 3.0, 4.0, 3.0, 4.0, 5.0, 3.0, 4.0, 4.0, 2.0, 3.0, 2.0, 4.0, 5.0, 1.0, 4.0, 3.0, 3.0, 5.0, 5.0, 4.0, 3.0, 2.0, 5.0, 4.0, 4.0, 3.0, 4.0, 4.0, 1.0, 3.0, 4.0, 4.0, 3.0, 5.0, 2.0, 3.0, 4.0, 4.0, 3.0, 4.0, 4.0, 5.0, 2.0, 5.0, 4.0, 4.0, 4.0, 1.0, 3.0, 5.0, 1.0, 3.0, 4.0, 4.0, 4.0, 2.0, 3.0, 3.0, 2.0, 2.0, 4.0, 

# test matrix oluşturma

In [26]:
for i in range(len(random_users_id_list)):
    test_matrix[random_users_id_list[i]][users_first_rating_movie[i]]=train_matrix[random_users_id_list[i]][users_first_rating_movie[i]]
    train_matrix[random_users_id_list[i]][users_first_rating_movie[i]]=0

In [27]:
print(random_users_id_list)

[4, 12, 13, 17, 19, 32, 40, 59, 70, 82, 100, 110, 119, 128, 130, 148, 150, 159, 160, 175, 210, 213, 224, 225, 232, 242, 250, 275, 277, 278, 295, 305, 317, 325, 326, 327, 332, 355, 369, 386, 395, 400, 420, 431, 438, 460, 462, 481, 491, 492, 507, 511, 519, 549, 550, 556, 559, 563, 584, 598, 604, 616, 630, 643, 652, 658, 690, 721, 722, 725, 745, 750, 755, 757, 784, 795, 801, 806, 815, 816, 823, 852, 863, 872, 877, 880, 883, 890, 912, 913, 917, 919, 933, 935]


In [28]:
for i in random_users_id_list:
    print(np.sum(test_matrix[i]), end=", ")

3.0, 3.0, 5.0, 5.0, 3.0, 3.0, 4.0, 5.0, 3.0, 4.0, 3.0, 4.0, 4.0, 4.0, 5.0, 3.0, 5.0, 4.0, 2.0, 5.0, 3.0, 5.0, 5.0, 5.0, 3.0, 4.0, 4.0, 5.0, 3.0, 3.0, 5.0, 4.0, 2.0, 3.0, 4.0, 3.0, 4.0, 5.0, 3.0, 4.0, 4.0, 2.0, 3.0, 2.0, 4.0, 5.0, 1.0, 4.0, 3.0, 3.0, 5.0, 5.0, 4.0, 3.0, 2.0, 5.0, 4.0, 4.0, 3.0, 4.0, 4.0, 1.0, 3.0, 4.0, 4.0, 3.0, 5.0, 2.0, 3.0, 4.0, 4.0, 3.0, 4.0, 4.0, 5.0, 2.0, 5.0, 4.0, 4.0, 4.0, 1.0, 3.0, 5.0, 1.0, 3.0, 4.0, 4.0, 4.0, 2.0, 3.0, 3.0, 2.0, 2.0, 4.0, 

In [29]:
for i in range(94):
    print(train_matrix[random_users_id_list[i]][users_first_rating_movie[i]], end=", ")

0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 

# test ve train matrix 'i oluşturuldu test+train=base(MLP)

In [146]:
# 1-user_similart
user_similarity = pairwise_distances(train_matrix, metric='correlation')
user_similarity=1-user_similarity
print('shape: ',user_similarity.shape)
print('type: ',type(user_similarity))
user_similarity

shape:  (943, 943)
type:  <class 'numpy.ndarray'>


array([[ 1.        ,  0.09131022, -0.00581008, ...,  0.00910694,
         0.10831478,  0.30758436],
       [ 0.09131022,  1.        ,  0.10288466, ...,  0.1627796 ,
         0.1442557 ,  0.03401889],
       [-0.00581008,  0.10288466,  1.        , ...,  0.01597579,
         0.09786267, -0.01432321],
       ...,
       [ 0.00910694,  0.1627796 ,  0.01597579, ...,  1.        ,
         0.0242929 , -0.0044431 ],
       [ 0.10831478,  0.1442557 ,  0.09786267, ...,  0.0242929 ,
         1.        ,  0.09312477],
       [ 0.30758436,  0.03401889, -0.01432321, ..., -0.0044431 ,
         0.09312477,  1.        ]])

# diogonalları 0'lama

In [93]:
len(user_similarity)correlationjaccard

SyntaxError: invalid syntax (<ipython-input-93-1ceac2c51665>, line 1)

In [94]:
for i in range(len(user_similarity)):
    for j in range(len(user_similarity)):
        if i == j:
            user_similarity[i][j]=0
        else:
            continue
            

In [95]:
for i in range(len(user_similarity)):
    print(user_similarity[i][i], end=" ,")

0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,

In [96]:
user_similarity.sort

<function ndarray.sort>

In [160]:
a=user_similarity.argsort()

In [166]:
a[0][-11:]

array([ 91,  63, 513, 434, 822, 737, 863, 267, 456, 915,   0], dtype=int64)

In [158]:
similar_n = user_similarity.argsort()[:,-11:][:,::-1]

In [163]:
similar_n.shape

(943, 11)

In [101]:
user_similarity[0][915]

0.47600819419518414

In [102]:
user_similarity[0][681]

0.40383770391586093

In [103]:
user_similarity[1][930]

0.45041621983950075

In [120]:
ml=[1,2,5,8,9,123,62,1231,11]

In [122]:
arr

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
arr=np.array([[4,5,6],[3,2,1],[7,8,9]])

In [125]:
arr

array([[4, 5, 6],
       [3, 2, 1],
       [7, 8, 9]])

In [124]:
arr.argsort()

array([[0, 1, 2],
       [2, 1, 0],
       [0, 1, 2]], dtype=int64)

In [134]:
st=arr.argsort()[:,1:][:,::-1]# doğru olan

In [135]:
st

array([[2, 1],
       [0, 1],
       [2, 1]], dtype=int64)

In [136]:
def predict_user_user(train_matrix, user_similarity, n_similar = 10):
    # sort edip ters indexlerini ters çeviriyor seçilen en yakın user sayısına göre
    similar_n = user_similarity.argsort()[:,n_similar:][:,::-1]# kontrol et
    # pred matrix'i oluşturuluyor
    pred = np.zeros((n_users_base,n_items_base))
    
    for i,users in enumerate(similar_n):# pred yapılıyor
        similar_users_indexes = users
        similarity_n = user_similarity[i,similar_users_indexes]
        matrix_n = train_matrix[similar_users_indexes,:]
        rated_items = similarity_n[:,np.newaxis].T.dot(matrix_n - matrix_n.mean(axis=1)[:,np.newaxis])/ similarity_n.sum()
        pred[i,:]  = rated_items
        
    return pred

In [137]:

predictions = predict_user_user(train_matrix,user_similarity, 10) + train_matrix.mean(axis=1)[:, np.newaxis]# 30 olması daha iyi
print('predictions shape ',predictions.shape)

predictions

predictions shape  (943, 1682)


array([[ 2.33767857e+00,  1.00343630e+00,  6.90377618e-01, ...,
         2.53183413e-01,  2.61061179e-01,  2.62545789e-01],
       [ 1.41526309e+00,  1.80970731e-01,  2.24765095e-01, ...,
        -4.67950259e-02, -4.93227574e-02, -5.11822644e-02],
       [ 7.52522093e-01,  9.88781053e-02,  1.32108385e-01, ...,
        -4.06503173e-02, -5.11639486e-02, -5.41599406e-02],
       ...,
       [ 2.05732845e+00,  2.23032870e-01,  2.37106516e-01, ...,
        -1.56865964e-01, -1.56376520e-01, -1.55295235e-01],
       [ 1.58130384e+00,  4.67931344e-01,  1.88863299e-01, ...,
        -8.09173306e-02, -7.77886869e-02, -8.09400621e-02],
       [ 2.17792590e+00,  8.89994422e-01,  5.04955081e-01, ...,
        -5.80273476e-03,  3.09686880e-03,  2.13484415e-03]])

In [139]:
predicted_ratings = predictions[test_matrix.nonzero()]

test_truth = test_matrix[test_matrix.nonzero()]

In [140]:
math.sqrt(mean_squared_error(predicted_ratings,test_truth))

2.270698330657104

In [141]:
test_truth

array([3., 3., 5., 5., 3., 3., 4., 5., 3., 4., 3., 4., 4., 4., 5., 3., 5.,
       4., 2., 5., 3., 5., 5., 5., 3., 4., 4., 5., 3., 3., 5., 4., 2., 3.,
       4., 3., 4., 5., 3., 4., 4., 2., 3., 2., 4., 5., 1., 4., 3., 3., 5.,
       5., 4., 3., 2., 5., 4., 4., 3., 4., 4., 1., 3., 4., 4., 3., 5., 2.,
       3., 4., 4., 3., 4., 4., 5., 2., 5., 4., 4., 4., 1., 3., 5., 1., 3.,
       4., 4., 4., 2., 3., 3., 2., 2., 4.])

In [142]:
predicted_ratings[0]

0.4067770544564173

In [143]:
predicted_ratings[1]

2.6721274200259315

In [144]:
predicted_ratings[2]

1.8099696717468028

In [145]:
test_truth[0]

3.0

In [117]:
test_truth[1]

3.0

In [118]:
test_truth[2]

5.0

In [55]:
predicted_ratings

array([ 1.85063912,  2.63360571,  3.066485  ,  2.25646171,  2.59466506,
        0.50684754,  1.20182777,  2.3882842 , -0.12483748,  3.0659562 ,
        2.78152761,  1.02567644,  0.38528735,  1.34331083,  2.8484309 ,
        2.46390558,  1.80540855,  2.63724722, -0.04356276,  2.29235771,
        1.31918191,  1.57493698,  1.2080226 ,  1.1829724 ,  3.05889094,
        2.50377998,  2.00574654,  1.66956401,  2.15552882,  2.10063094,
        2.86354878,  3.58501237,  2.739144  ,  2.11016871,  2.72097157,
        1.15832569,  2.07050605,  3.47656693,  1.42033111,  2.95736734,
        1.01088546,  1.67351749,  1.88601515,  1.47599978,  0.66799753,
        2.02357752,  0.63110407,  2.33035962,  1.94221257, -0.02681972,
        3.6430619 ,  3.31950498,  2.11237969,  1.33640263,  2.38703681,
        2.72664119,  2.38052412,  0.20570373,  0.61871144,  0.20813669,
        2.92932521,  1.66005864,  1.82696953,  1.42910336,  2.42398138,
        2.34766048,  1.24804254,  0.21541119,  2.4439872 ,  1.18

In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.metrics import mean_squared_error
import math

In [3]:
rs_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']

ratings_base = pd.read_csv('ml-1m/ratings.dat', sep='::', names=rs_cols, encoding='latin-1')
ratings_test = pd.read_csv('ml-1m/ratings.dat', sep='::', names=rs_cols, encoding='latin-1')

D:\anaconda3\lib\site-packages\ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until
D:\anaconda3\lib\site-packages\ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.


In [13]:
ratings_base.head()

user_id  movie_id  rating  unix_timestamp
0        1      1193       5       978300760
1        1       661       3       978302109
2        1       914       3       978301968
3        1      3408       4       978300275
4        1      2355       5       978824291

In [6]:
n_users_base = ratings_base['user_id'].unique().max()
n_items_base = ratings_base['movie_id'].unique().max()

n_users_base,n_items_base

(6040, 3952)

In [7]:
n_users_test = ratings_test['user_id'].unique().max()
n_items_test = ratings_test['movie_id'].unique().max()
n_users_test,n_items_test

(6040, 3952)

In [8]:
train_matrix = np.zeros((n_users_base, n_items_base))
test_matrix = np.zeros((n_users_test, n_items_test))

In [9]:
for line in ratings_base.itertuples():
    train_matrix[line[1]-1,line[2]-1] = line[3]

In [10]:
test_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
train_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [3., 0., 0., ..., 0., 0., 0.]])

In [14]:
n_users_base

6040

In [15]:
n_items_base

3952

In [16]:
random_users_id_list=[]
while True:
    rnd=np.random.randint(6040)
    if len(random_users_id_list) < 604:
        if rnd in random_users_id_list:
            continue
        else:
            random_users_id_list.append(rnd)
    else:
        break

In [17]:
random_users_id_list.sort()

In [18]:
random_users_id_list

[6,
 8,
 22,
 41,
 56,
 73,
 83,
 86,
 106,
 108,
 120,
 123,
 131,
 135,
 136,
 143,
 148,
 164,
 175,
 177,
 181,
 184,
 198,
 199,
 203,
 220,
 228,
 245,
 254,
 278,
 279,
 283,
 284,
 287,
 308,
 311,
 313,
 320,
 326,
 329,
 330,
 349,
 366,
 431,
 442,
 446,
 458,
 473,
 478,
 482,
 487,
 518,
 527,
 533,
 547,
 560,
 563,
 564,
 567,
 570,
 582,
 623,
 624,
 635,
 650,
 656,
 693,
 709,
 726,
 729,
 730,
 752,
 756,
 757,
 766,
 771,
 789,
 805,
 830,
 842,
 869,
 875,
 883,
 898,
 910,
 921,
 926,
 930,
 947,
 959,
 961,
 976,
 977,
 991,
 1002,
 1006,
 1015,
 1018,
 1025,
 1051,
 1053,
 1068,
 1074,
 1095,
 1115,
 1116,
 1123,
 1127,
 1153,
 1172,
 1177,
 1179,
 1180,
 1182,
 1183,
 1186,
 1189,
 1194,
 1203,
 1206,
 1207,
 1218,
 1219,
 1229,
 1235,
 1236,
 1247,
 1248,
 1249,
 1253,
 1262,
 1264,
 1265,
 1268,
 1281,
 1282,
 1293,
 1329,
 1330,
 1334,
 1347,
 1359,
 1370,
 1373,
 1395,
 1400,
 1405,
 1408,
 1411,
 1419,
 1420,
 1421,
 1433,
 1435,
 1461,
 1478,
 1483,
 1501

In [19]:
users_first_rating_movie=[]

In [20]:
for user in random_users_id_list:
    for item in range(n_items_base):
        if train_matrix[user][item] == 0:
            continue
        else:
            users_first_rating_movie.append(item)
            break

In [21]:
print(random_users_id_list)


[6, 8, 22, 41, 56, 73, 83, 86, 106, 108, 120, 123, 131, 135, 136, 143, 148, 164, 175, 177, 181, 184, 198, 199, 203, 220, 228, 245, 254, 278, 279, 283, 284, 287, 308, 311, 313, 320, 326, 329, 330, 349, 366, 431, 442, 446, 458, 473, 478, 482, 487, 518, 527, 533, 547, 560, 563, 564, 567, 570, 582, 623, 624, 635, 650, 656, 693, 709, 726, 729, 730, 752, 756, 757, 766, 771, 789, 805, 830, 842, 869, 875, 883, 898, 910, 921, 926, 930, 947, 959, 961, 976, 977, 991, 1002, 1006, 1015, 1018, 1025, 1051, 1053, 1068, 1074, 1095, 1115, 1116, 1123, 1127, 1153, 1172, 1177, 1179, 1180, 1182, 1183, 1186, 1189, 1194, 1203, 1206, 1207, 1218, 1219, 1229, 1235, 1236, 1247, 1248, 1249, 1253, 1262, 1264, 1265, 1268, 1281, 1282, 1293, 1329, 1330, 1334, 1347, 1359, 1370, 1373, 1395, 1400, 1405, 1408, 1411, 1419, 1420, 1421, 1433, 1435, 1461, 1478, 1483, 1501, 1503, 1528, 1531, 1535, 1536, 1570, 1618, 1652, 1657, 1658, 1691, 1694, 1700, 1701, 1706, 1710, 1718, 1736, 1743, 1750, 1751, 1753, 1778, 1781, 1782, 1785,

In [22]:
print(users_first_rating_movie)

[5, 0, 0, 5, 46, 33, 109, 20, 110, 0, 0, 33, 0, 0, 2, 355, 0, 49, 1078, 10, 0, 8, 2, 7, 0, 110, 1, 0, 0, 109, 33, 0, 21, 20, 33, 16, 0, 0, 35, 259, 5, 0, 110, 2, 5, 526, 313, 0, 0, 110, 38, 0, 0, 10, 69, 31, 149, 174, 109, 1, 0, 0, 16, 109, 15, 42, 110, 0, 6, 5, 0, 0, 0, 31, 10, 23, 259, 109, 46, 0, 18, 5, 31, 0, 1, 5, 2, 0, 0, 5, 46, 0, 46, 10, 28, 1090, 2, 4, 109, 16, 0, 10, 161, 0, 0, 0, 0, 13, 191, 3, 295, 259, 0, 0, 0, 38, 111, 23, 23, 0, 267, 9, 0, 0, 440, 18, 0, 276, 480, 24, 0, 0, 0, 313, 33, 0, 0, 1, 16, 0, 0, 33, 1, 16, 33, 33, 33, 28, 152, 5, 0, 0, 0, 42, 2, 24, 0, 0, 5, 1, 0, 316, 94, 5, 528, 222, 0, 2, 33, 0, 5, 23, 16, 2, 222, 0, 10, 109, 0, 109, 0, 200, 44, 109, 109, 0, 0, 46, 0, 24, 0, 31, 0, 0, 4, 18, 0, 69, 222, 0, 149, 0, 0, 5, 0, 6, 10, 0, 2, 2, 0, 0, 0, 3, 109, 0, 10, 5, 104, 222, 299, 222, 104, 2, 150, 0, 1, 0, 59, 2, 33, 16, 588, 10, 0, 0, 112, 252, 110, 259, 31, 10, 23, 38, 57, 0, 109, 0, 2, 23, 298, 0, 6, 222, 109, 0, 0, 0, 5, 5, 38, 6, 967, 0, 2, 0, 0, 69, 0, 

In [23]:
for i in range(94):
    print(train_matrix[random_users_id_list[i]][users_first_rating_movie[i]], end=", ")

4.0, 5.0, 4.0, 4.0, 4.0, 2.0, 5.0, 1.0, 3.0, 4.0, 5.0, 5.0, 5.0, 2.0, 5.0, 3.0, 3.0, 5.0, 4.0, 5.0, 5.0, 3.0, 3.0, 3.0, 4.0, 2.0, 3.0, 5.0, 4.0, 4.0, 1.0, 5.0, 5.0, 3.0, 4.0, 3.0, 4.0, 2.0, 4.0, 5.0, 4.0, 5.0, 4.0, 2.0, 4.0, 5.0, 4.0, 5.0, 5.0, 3.0, 3.0, 4.0, 5.0, 5.0, 3.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, 4.0, 4.0, 3.0, 5.0, 3.0, 5.0, 5.0, 5.0, 3.0, 4.0, 4.0, 2.0, 5.0, 3.0, 5.0, 4.0, 3.0, 4.0, 5.0, 4.0, 4.0, 4.0, 3.0, 4.0, 3.0, 5.0, 4.0, 3.0, 5.0, 4.0, 

In [24]:
for i in range(len(random_users_id_list)):
    test_matrix[random_users_id_list[i]][users_first_rating_movie[i]]=train_matrix[random_users_id_list[i]][users_first_rating_movie[i]]
    train_matrix[random_users_id_list[i]][users_first_rating_movie[i]]=0

In [25]:
print(random_users_id_list)

[6, 8, 22, 41, 56, 73, 83, 86, 106, 108, 120, 123, 131, 135, 136, 143, 148, 164, 175, 177, 181, 184, 198, 199, 203, 220, 228, 245, 254, 278, 279, 283, 284, 287, 308, 311, 313, 320, 326, 329, 330, 349, 366, 431, 442, 446, 458, 473, 478, 482, 487, 518, 527, 533, 547, 560, 563, 564, 567, 570, 582, 623, 624, 635, 650, 656, 693, 709, 726, 729, 730, 752, 756, 757, 766, 771, 789, 805, 830, 842, 869, 875, 883, 898, 910, 921, 926, 930, 947, 959, 961, 976, 977, 991, 1002, 1006, 1015, 1018, 1025, 1051, 1053, 1068, 1074, 1095, 1115, 1116, 1123, 1127, 1153, 1172, 1177, 1179, 1180, 1182, 1183, 1186, 1189, 1194, 1203, 1206, 1207, 1218, 1219, 1229, 1235, 1236, 1247, 1248, 1249, 1253, 1262, 1264, 1265, 1268, 1281, 1282, 1293, 1329, 1330, 1334, 1347, 1359, 1370, 1373, 1395, 1400, 1405, 1408, 1411, 1419, 1420, 1421, 1433, 1435, 1461, 1478, 1483, 1501, 1503, 1528, 1531, 1535, 1536, 1570, 1618, 1652, 1657, 1658, 1691, 1694, 1700, 1701, 1706, 1710, 1718, 1736, 1743, 1750, 1751, 1753, 1778, 1781, 1782, 1785,

In [26]:
for i in random_users_id_list:
    print(np.sum(test_matrix[i]), end=", ")

4.0, 5.0, 4.0, 4.0, 4.0, 2.0, 5.0, 1.0, 3.0, 4.0, 5.0, 5.0, 5.0, 2.0, 5.0, 3.0, 3.0, 5.0, 4.0, 5.0, 5.0, 3.0, 3.0, 3.0, 4.0, 2.0, 3.0, 5.0, 4.0, 4.0, 1.0, 5.0, 5.0, 3.0, 4.0, 3.0, 4.0, 2.0, 4.0, 5.0, 4.0, 5.0, 4.0, 2.0, 4.0, 5.0, 4.0, 5.0, 5.0, 3.0, 3.0, 4.0, 5.0, 5.0, 3.0, 5.0, 5.0, 4.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, 4.0, 4.0, 3.0, 5.0, 3.0, 5.0, 5.0, 5.0, 3.0, 4.0, 4.0, 2.0, 5.0, 3.0, 5.0, 4.0, 3.0, 4.0, 5.0, 4.0, 4.0, 4.0, 3.0, 4.0, 3.0, 5.0, 4.0, 3.0, 5.0, 4.0, 3.0, 4.0, 2.0, 2.0, 3.0, 5.0, 5.0, 3.0, 4.0, 4.0, 4.0, 5.0, 5.0, 4.0, 2.0, 3.0, 5.0, 5.0, 3.0, 5.0, 4.0, 4.0, 4.0, 3.0, 3.0, 4.0, 4.0, 2.0, 3.0, 4.0, 3.0, 2.0, 2.0, 3.0, 4.0, 4.0, 4.0, 4.0, 5.0, 3.0, 5.0, 5.0, 5.0, 2.0, 4.0, 4.0, 3.0, 4.0, 5.0, 4.0, 5.0, 4.0, 4.0, 4.0, 1.0, 4.0, 5.0, 4.0, 2.0, 4.0, 2.0, 5.0, 4.0, 4.0, 4.0, 3.0, 5.0, 4.0, 3.0, 4.0, 4.0, 4.0, 4.0, 3.0, 4.0, 5.0, 5.0, 5.0, 5.0, 2.0, 2.0, 5.0, 4.0, 5.0, 5.0, 2.0, 3.0, 4.0, 3.0, 4.0, 3.0, 5.0, 5.0, 4.0, 5.0, 3.0, 5.0, 4.0, 4.0, 5.0, 2.0, 4.0, 4.0, 3.0, 5.0, 4.0, 

In [27]:
for i in range(94):
    print(train_matrix[random_users_id_list[i]][users_first_rating_movie[i]], end=", ")

0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 

In [29]:
# 1-user_similart
user_similarity = pairwise_distances(train_matrix, metric='cosine')
user_similarity=1-user_similarity
print('shape: ',user_similarity.shape)
print('type: ',type(user_similarity))
user_similarity

shape:  (6040, 6040)
type:  <class 'numpy.ndarray'>


array([[1.        , 0.09638153, 0.12060981, ..., 0.        , 0.17460369,
        0.13359025],
       [0.09638153, 1.        , 0.1514786 , ..., 0.06611767, 0.0664575 ,
        0.21827563],
       [0.12060981, 0.1514786 , 1.        , ..., 0.12023352, 0.09467506,
        0.13314404],
       ...,
       [0.        , 0.06611767, 0.12023352, ..., 1.        , 0.16171426,
        0.09930008],
       [0.17460369, 0.0664575 , 0.09467506, ..., 0.16171426, 1.        ,
        0.22833237],
       [0.13359025, 0.21827563, 0.13314404, ..., 0.09930008, 0.22833237,
        1.        ]])

In [30]:
for i in range(len(user_similarity)):
    for j in range(len(user_similarity)):
        if i == j:
            user_similarity[i][j]=0
        else:
            continue
            

In [31]:
for i in range(len(user_similarity)):
    print(user_similarity[i][i], end=" ,")

0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,

 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0 ,0.0

In [35]:
def predict_user_user(train_matrix, user_similarity, n_similar=30):
    # sort edip ters indexlerini ters çeviriyor seçilen en yakın user sayısına göre
    similar_n = user_similarity.argsort()[:,n_similar:][:,::-1]# kontrol et
    # pred matrix'i oluşturuluyor
    pred = np.zeros((n_users_base,n_items_base))
    
    for i,users in enumerate(similar_n):# pred yapılıyor
        similar_users_indexes = users
        similarity_n = user_similarity[i,similar_users_indexes]
        matrix_n = train_matrix[similar_users_indexes,:]
        rated_items = similarity_n[:,np.newaxis].T.dot(matrix_n - matrix_n.mean(axis=1)[:,np.newaxis])/ similarity_n.sum()
        pred[i,:]  = rated_items
        
    return pred

In [36]:
predictions = predict_user_user(train_matrix,user_similarity, 30) + train_matrix.mean(axis=1)[:, np.newaxis]# 30 olması daha iyi
print('predictions shape ',predictions.shape)

predictions

predictions shape  (6040, 3952)


array([[ 1.72618284,  0.3669082 ,  0.15464969, ..., -0.08897578,
        -0.10445441,  0.14311739],
       [ 1.5198873 ,  0.41302634,  0.22270161, ..., -0.03125381,
        -0.05083353,  0.22091092],
       [ 1.50890854,  0.35922931,  0.15123694, ..., -0.09588757,
        -0.11519368,  0.11498493],
       ...,
       [ 1.54341024,  0.27647603,  0.10202431, ..., -0.13030558,
        -0.15099003,  0.09597635],
       [ 1.58269725,  0.3868667 ,  0.18575528, ..., -0.03644404,
        -0.05606499,  0.18425771],
       [ 1.70370085,  0.53045888,  0.35494243, ...,  0.1553014 ,
         0.13638447,  0.41736532]])

In [37]:
predicted_ratings = predictions[test_matrix.nonzero()]

test_truth = test_matrix[test_matrix.nonzero()]

In [38]:
math.sqrt(mean_squared_error(predicted_ratings,test_truth))

2.958535700276364

In [39]:
test_truth

array([4., 5., 4., 4., 4., 2., 5., 1., 3., 4., 5., 5., 5., 2., 5., 3., 3.,
       5., 4., 5., 5., 3., 3., 3., 4., 2., 3., 5., 4., 4., 1., 5., 5., 3.,
       4., 3., 4., 2., 4., 5., 4., 5., 4., 2., 4., 5., 4., 5., 5., 3., 3.,
       4., 5., 5., 3., 5., 5., 4., 5., 4., 5., 3., 5., 4., 4., 4., 3., 5.,
       3., 5., 5., 5., 3., 4., 4., 2., 5., 3., 5., 4., 3., 4., 5., 4., 4.,
       4., 3., 4., 3., 5., 4., 3., 5., 4., 3., 4., 2., 2., 3., 5., 5., 3.,
       4., 4., 4., 5., 5., 4., 2., 3., 5., 5., 3., 5., 4., 4., 4., 3., 3.,
       4., 4., 2., 3., 4., 3., 2., 2., 3., 4., 4., 4., 4., 5., 3., 5., 5.,
       5., 2., 4., 4., 3., 4., 5., 4., 5., 4., 4., 4., 1., 4., 5., 4., 2.,
       4., 2., 5., 4., 4., 4., 3., 5., 4., 3., 4., 4., 4., 4., 3., 4., 5.,
       5., 5., 5., 2., 2., 5., 4., 5., 5., 2., 3., 4., 3., 4., 3., 5., 5.,
       4., 5., 3., 5., 4., 4., 5., 2., 4., 4., 3., 5., 4., 3., 4., 4., 4.,
       5., 2., 4., 4., 1., 3., 4., 4., 5., 3., 4., 5., 5., 4., 5., 4., 4.,
       4., 4., 2., 4., 5.

In [40]:
predicted_ratings

array([ 8.07832142e-01,  1.55984157e+00,  1.67911823e+00,  8.64904136e-01,
        8.56453631e-01,  1.22303586e+00,  1.98428879e+00,  9.42631951e-01,
        1.30050531e+00,  1.55574557e+00,  1.45990769e+00,  1.27265884e+00,
        1.79660457e+00,  1.80785207e+00,  3.07188132e-01,  1.62109238e+00,
        2.02031042e+00,  1.64346080e+00,  1.53072034e+00,  7.52205333e-01,
        1.58024114e+00, -4.58557922e-02,  4.62507718e-01, -1.06156208e-01,
        1.92155991e+00,  8.84685402e-01,  4.75727157e-01,  1.67578244e+00,
        1.68522790e+00,  2.11181767e+00,  1.37590190e+00,  1.84416141e+00,
        2.50086549e-01,  1.03318900e+00,  1.26216280e+00,  5.55337724e-01,
        1.72398571e+00,  1.57674552e+00,  9.00117766e-01,  2.52583552e+00,
        1.26543215e+00,  1.56441430e+00,  1.11635203e+00,  2.78013359e-01,
        7.36858332e-01,  2.18477565e+00,  8.88843323e-02,  1.76647723e+00,
        1.58655445e+00,  9.76859181e-01,  6.30903858e-01,  1.58995597e+00,
        2.08501291e+00,  

In [41]:
predicted_ratings[0]

0.8078321419084351

In [43]:
predicted_ratings[1]

1.5598415736942717

In [44]:
predicted_ratings[2]

1.6791182283957222

In [45]:
test_truth[0]

4.0

In [46]:
test_truth[1]

5.0

In [47]:
test_truth[2]

4.0